---
  - name: install the db and web package 
    yum: 
      name: 
        - "{{ ansible_local.custom.packages.db_package }}"
        - "{{ ansible_local.custom.packages.web_package }}"
      state: latest

  - name: start the database and ftp service
    service:
      name: "{{ ansible_local.custom.services.db_service }}"
      state: started
      enabled: true

  - name: start the ftp service
    service:
      name: "{{ ansible_local.custom.services.web_service }}"
      state: started
      enabled: true
